[mgr]
sort_by = "mtime"
linemode = "line_info"
sort_reverse = true
sort_dir_first = true
show_hidden = false
mouse_events = []

[opener]
image = [
	{ run = 'gtk4-launch fehcustom.desktop "$@"', orphan = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
prepend_rules = [
	{ mime = "application/pdf", use = "open" },
	{ mime = "application/json", use = "edit" },
	{ name = "*.html", use = [ "open" ] },
]
rules = [
	{ mime = "image/*", use = "image" },
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
]
append_rules = [
	{ name = "*", use = ["edit", "open", "image", "play"]}
]
